name: CI Pipeline

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: .github/actions/java-setup
      - name: Run linters
        run: ./gradlew checkstyleMain spotlessCheck
        continue-on-error: false

  assemble:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: lint
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: .github/actions/java-setup
      - name: Assemble
        run: ./gradlew assemble
        continue-on-error: false

  spotbugs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: assemble
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: .github/actions/java-setup
      - name: Run linters
        run: ./gradlew checkstyleMain spotlessCheck spotbugsMain
        continue-on-error: false

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: spotbugs
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: .github/actions/java-setup
      - name: Run tests
        run: ./gradlew test
        continue-on-error: false
